language: php
php:
  - "5.4"
  - "5.3"
branches:
  only:
    - master
env:
  global:
    - secure: "EdtuuYc6fmkvQsxtzs5qcjS5mzkxso9OVjNAtUnXBdGQg/FximxU4Xgrb1ouyMc+NAUSP0OmsHugFcrbwq0+1OIzOkDPa8setpyUQ0erIo4plT7L8WRNKK4r0xWeA1YTVpeug8IfUcZbj5vwhRnV05GH+z1nITpSBPUPJR5eEcs="
    - "REPOSITORY=visualcaptcha-multiple"
before_script:
  - composer install
after_success:
    "curl --data 'deploy={\"repository\":\"'$REPOSITORY'\",\"branch\":\"'$TRAVIS_BRANCH'\"}' http://githooks.emotionloop.com/?k=$AUTH_KEY"
